# Site settings
title: photos.n4.sk
email: hello@n4.sk
#description: "Even if you're not doing anything wrong, you are being watched and recorded. 'Edward Snowden'"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://photos.n4.sk" # the base hostname & protocol for your site
github_username:  nagyfrantisek
facebook_username:  nfrantisek

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate

paginate: 9
paginate_path: "/page:num/"
